---
subnets_rhisam:
  - name: "labsubnet"
    description: "Front side for client apps"
    network_type: "IPv4"
    network: 192.168.252.0
    prefix: 22
    mask: 255.255.252.0
    gateway: 192.168.252.1
    dns_primary: 192.168.252.5
    dns_secondary: 192.168.252.6
    ipam: "Internal DB"
    from_ip: 192.168.252.100
    to_ip: 192.168.252.199
    boot_mode: "Static"
    discovery_capsule: "{{ satellite_fqdn }}"
    tftp_capsule: "{{ satellite_fqdn }}"
    dns_capsule: "{{ satellite_fqdn }}"
    template_capsule: "{{ satellite_fqdn }}"
    domains:
      - "{{ satellite_domain }}"
    locations:
      - "{{ satellite_location }}"
    organizations:
      - "{{ satellite_organization }}"

subnets_user:
  - name: "azuresubnet"
    description: "Subnet for azure resource group"
    network_type: "IPv4"
    network: 10.3.1.0
    prefix: 24
    mask: 255.255.255.0
    gateway: 10.3.1.1
    dns_primary: 192.166.252.5
    dns_secondary: 192.168.252.6
    ipam: "Internal DB"
    from_ip: 10.3.1.10
    to_ip: 10.3.1.50
    boot_mode: "Static"
    discovery_capsule: "{{ capsule_fqdn }}"
    tftp_capsule: "{{ capsule_fqdn }}"
    dns_capsule: "{{ capsule_fqdn }}"
    template_capsule: "{{ capsule_fqdn }}"
    domains:
      - "{{ satellite_domain }}"
    locations:
      - "{{ capsule_location }}"
    organizations:
      - "{{ satellite_organization }}"
