---
# Ensure the SCAP policy configuation

- name: "Ensure the scap policies configuration"
  when: scap_policies is defined and (scap_policies | length) > 0
  ansible.builtin.include_tasks: "ensure_scap_policy.yml"
  loop: "{{ scap_policies }}"
  loop_control:
    loop_var: scap_policy
  no_log: true
  tags:
    - tags_rhisam
    - tags_scap_config
    - tags_scap_policies
