---
# If there are repositories enabled for third party repos
# disable the repos and ensure only repositories for Red Hat Satellite are enabled


- name: "Ensure the proper repositories are enabled"
  community.general.rhsm_repository:
    name: "{{ repository_ids }}"
    state: enabled
    purge: true

- name: "Ensure the release is not set" # noqa: no-changed-when
  ansible.builtin.command: "subscription-manager release --unset"

- name: "Clean the yum metadata" # noqa: no-changed-when
  ansible.builtin.command: "yum clean all"
