---
# Tell the yaml linter to ignore long lines
# yamllint disable rule:line-length

# These operations do not play well with the ansible conventions for changes and shell pipes
# This has been tested extensively on RHEL8 and RHEL9 and works as expected.

- name: "Clean up old keytabs"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/etc/foreman-proxy/freeipa.keytab"
    - "freeipa.keytab"

- name: "Setup satellite realm user"  # noqa: no-changed-when risky-shell-pipe
  ansible.builtin.shell: "echo '{{ ipa_admin_password }}' | kinit {{ ipa_admin_principal }}; echo '{{ ipa_admin_password }}' | /usr/sbin/foreman-prepare-realm admin {{ foreman_proxy_realm_principal }}"
  register: result

- name: "Wait for keytab generation and retrieval"
  ansible.builtin.wait_for:
    path: "freeipa.keytab"

- name: "Ensure the foreman-proxy directory exists"  # noqa: no-changed-when risky-shell-pipe
  ansible.builtin.file:
    path: "/etc/foreman-proxy"
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"

- name: "Move the keytab to the foreman-proxy directory"  # noqa: no-changed-when risky-shell-pipe
  ansible.builtin.copy:
    src: "freeipa.keytab"
    dest: /etc/foreman-proxy/freeipa.keytab
    owner: foreman-proxy
    group: foreman-proxy
    mode: "0600"
    remote_src: true

- name: "Test the new keytab" # noqa: no-changed-when risky-shell-pipe
  ansible.builtin.command: "kinit -kt /etc/foreman-proxy/freeipa.keytab {{ foreman_proxy_realm_principal }}"
  register: result

- name: "Assert Success"
  ansible.builtin.assert:
    that:
      - result.stdout == ""


- name: "Copy the ipa ca-certificates to the trust directory"
  ansible.builtin.copy:
    src: /etc/ipa/ca.crt
    dest: /etc/pki/ca-trust/source/anchors/ipa.crt
    remote_src: true
    owner: root
    group: root
    mode: '0644'

- name: "Enable the CA trust" # noqa: no-changed-when risky-shell-pipe
  ansible.builtin.command: "update-ca-trust enable"

- name: "Update the CA trust" # noqa: no-changed-when risky-shell-pipe
  ansible.builtin.command: "update-ca-trust"

- name: "Set up IdM DNS lookup zone to allow foreman proxy to update DNS"
  redhat.rhel_idm.ipadnszone:
    ipaadmin_principal: "{{ ipa_admin_principal }}"
    ipaadmin_password: "{{ ipa_admin_password }}"
    name: "{{ ipa_dns_zone }}"
    update_policy: "{{ foreman_proxy_bind_update_policy }}"
    allow_sync_ptr: true
    dynamic_update: true

- name: "Set up IdM reverse lookup zone to allow foreman proxy to update DNS"
  redhat.rhel_idm.ipadnszone:
    ipaadmin_principal: "{{ ipa_admin_principal }}"
    ipaadmin_password: "{{ ipa_admin_password }}"
    name: "{{ ipa_dns_reverse_zone }}"
    update_policy: "{{ foreman_proxy_bind_update_policy_reverse }}"
    allow_sync_ptr: true
    dynamic_update: true
