---
# setup the server for the installation of Satellite or Capsule
# Supports RHEL8 running Satellite 6.11 or greater


- name: "Ensure satellite reposistories are enabled"
  ansible.builtin.import_tasks: "ensure_repositories.yml"
  tags:
    - tags_rhisam
    - tags_satellite_pre
    - tags_satellite_pre_repos

- name: "Ensure satellite is using chronyd for time"
  ansible.builtin.import_tasks: "ensure_chronyd.yml"
  tags:
    - tags_rhisam
    - tags_satellite_pre
    - tags_satellite_pre_repos

- name: "Ensure satellite firewall ports are configured"
  ansible.builtin.import_tasks: ensure_firewalld_config.yml
  tags:
    - tags_rhisam
    - tags_satellite_pre
    - tags_satellite_pre_firewall

- name: "Ensure satellite binaries are installed"
  ansible.builtin.import_tasks: ensure_sat_binaries.yml
  tags:
    - tags_rhisam
    - tags_satellite_pre
    - tags_satellite_pre_packages

- name: "Ensure satellite is registered to Identity Management"
  ansible.builtin.import_tasks: ensure_idm_registered.yml
  tags:
    - tags_rhisam
    - tags_satellite_pre
    - tags_satellite_pre_idmclient

- name: "Ensure satellite certificates are generated"
  ansible.builtin.import_tasks: generate_certs.yml
  tags:
    - tags_rhisam
    - tags_satellite_pre
    - tags_satellite_pre_gen_certs

- name: "Ensure satellite certificates are validated"
  ansible.builtin.import_tasks: check_certs.yml
  tags:
    - tags_rhisam
    - tags_satellite_pre
    - tags_satellite_pre_check_certs

- name: "Ensure identity management realm is prepared for use with Satellite"
  ansible.builtin.import_tasks: foreman_prepare_realm.yml
  tags:
    - tags_rhisam
    - tags_satellite_pre
    - tags_satellite_pre_prepare_realm
