---
# This play ensures the state of global parameters
# state defaults to present

- name: "Ensure the state of global parameter - {{ global_parameter.name }}"
  redhat.satellite.global_parameter:
    username: "{{ satellite_username | default(omit) }}"
    password: "{{ satellite_password | default(omit) }}"
    use_gssapi: "{{ satellite_use_gssapi | default(omit) }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_validate_certs }}"
    name: "{{ global_parameter.name }}"
    value: "{{ global_parameter.value }}"
    parameter_type: "{{ global_parameter.parameter_type }}"
    hidden_value: "{{ global_parameter.hidden_value | default(omit) }}"
    state: "{{ global_parameter.state | default(omit) }}"
