---
# rhisam global parameters ensure RHISAM usecases behave appropriately
# Optional parameters can be added for your usecases

- name: "Configuring the global parameters"
  when: global_parameters is defined and (global_parameters | length) > 0
  ansible.builtin.include_tasks: "ensure_global_parameter.yml"
  loop: "{{ global_parameters }}"
  loop_control:
    loop_var: global_parameter
  no_log: true
  tags:
    - tags_rhisam
    - tags_provisioning_config
    - tags_global_parameters
