---
# These are the collections required by the builder
collections:
  - name: "ansible.posix"
    version: "*"
  - name: "ansible.utils"
    version: "*"
  - name: "community.general"
    version: "*"
  - name: "redhat.rhel_idm"
    version: ">=1.14.7"           # earlier versions fail with 'dns_over_tls' option error
  - name: "redhat.rhel_system_roles"
    version: "*"
  - name: "redhat.satellite"
    version: "*"
  - name: "redhat.satellite_operations"
    version: "*"
