---
# "Technically" these are products, but lets not quibble

# Red Hat Repositories
# - rhisam: make demos work - this pattern is used throughout
# - user: let's *you* do stuff - this pattern is used throughout
# the repo may or may not have a basearch or releasever - unfortunately, not a lot of consistency here
#

# Sync / Publish / Promote main control vars
# set to true to overide default to sync all content, publish all CVs and CCVs, and promote
# these are valuable in testing or in maintainance runs

# if you skip synchronization and
# you added kickstart repos to your product and content views
# satellite doesnt register the kickstart repos as synchronized content (obviously)
# new definitions like hostgroups then fail with bad content definitions
# avoid setting skip_sync_all or skip_publish_all in your variable file where possible
# call it with an extravar instead

skip_sync_all: false
last_sync_threshold_hours: 12

# Add additional content not needed for boostrap but still valuable and useful
# Can be set to false to skip managemet of repos, CVs and CCVs
repository_sets_rhisam:
  # RHEL 9.x kickstart
  - name: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS (Kickstart)"
    product: "Red Hat Enterprise Linux for x86_64"
    repository_list:
      - releasever: "9.2"
      - releasever: "9.3"
      - releasever: "9.4"

  - name: "Red Hat Enterprise Linux 9 for x86_64 - AppStream (Kickstart)"
    product: "Red Hat Enterprise Linux for x86_64"
    repository_list:
      - releasever: "9.2"
      - releasever: "9.3"
      - releasever: "9.4"

# RHEL9 repos
  - name: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS (RPMs)"
    product: "Red Hat Enterprise Linux for x86_64"
    repository_list:
      - releasever: "9"

  - name: "Red Hat Enterprise Linux 9 for x86_64 - AppStream (RPMs)"
    product: "Red Hat Enterprise Linux for x86_64"
    repository_list:
      - releasever: "9"

  - name: "Red Hat Enterprise Linux 9 for x86_64 - Supplementary (RPMs)"
    product: "Red Hat Enterprise Linux for x86_64"
    repository_list:
      - releasever: "9"

  - name: "Red Hat Satellite Client 6 for RHEL 9 x86_64 (RPMs)"
    product: "Red Hat Enterprise Linux for x86_64"

# RHEL 8.x kickstarts
  - name: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS (Kickstart)"
    product: "Red Hat Enterprise Linux for x86_64"
    repository_list:
      - releasever: "8.8"
      - releasever: "8.9"
      - releasever: "8.10"

  - name: "Red Hat Enterprise Linux 8 for x86_64 - AppStream (Kickstart)"
    product: "Red Hat Enterprise Linux for x86_64"
    repository_list:
      - releasever: "8.8"
      - releasever: "8.9"
      - releasever: "8.10"

# RHEL 8 Repos
  - name: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)"
    product: "Red Hat Enterprise Linux for x86_64"
    repository_list:
      - releasever: "8"

  - name: "Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)"
    product: "Red Hat Enterprise Linux for x86_64"
    repository_list:
      - releasever: "8"

  - name: "Red Hat Enterprise Linux 8 for x86_64 - Supplementary (RPMs)"
    product: "Red Hat Enterprise Linux for x86_64"
    repository_list:
      - releasever: "8"

  - name: "Red Hat Satellite Client 6 for RHEL 8 x86_64 (RPMs)"
    product: "Red Hat Enterprise Linux for x86_64"


# Ansible Automation Platform 2.4
  - name: "Red Hat Ansible Automation Platform 2.4 for RHEL 8 x86_64 (Files)"
    product: "Red Hat Ansible Automation Platform"


# Satellite 6.15
  - name: "Red Hat Satellite Capsule 6.15 for RHEL 8 x86_64 (RPMs)"
    product: "Red Hat Satellite Capsule"

  - name: "Red Hat Satellite Maintenance 6.15 for RHEL 8 x86_64 (RPMs)"
    product: "Red Hat Enterprise Linux for x86_64"


# JBoss Repos Needed for the JBoss server pipeline
  - name: "JBoss Enterprise Application Platform 7.4 (RHEL 8) (RPMs)"
    product: "JBoss Enterprise Application Platform"

# These repos are not necessarily needed for the default SOE test-destroy pipeline,
# however, if you want to do convert2rhel and LEAPP piplines, you need these
# Thes pull in the RHEL 7 and RHEL 8 repos and other Red Hat products

repository_sets_user:
# RHEL 7 Repos for convert2rhel and LEAPP_7_2_8
  - name: "Red Hat Enterprise Linux 7 Server (RPMs)"
    product: "Red Hat Enterprise Linux Server"
    repository_list:
      - releasever: "7Server"
        basearch: "x86_64"

  - name: "Red Hat Enterprise Linux 7 Server - Extras (RPMs)"
    product: "Red Hat Enterprise Linux Server"

  - name: "Red Hat Enterprise Linux 7 Server - RH Common (RPMs)"
    product: "Red Hat Enterprise Linux Server"
    repository_list:
      - releasever: "7Server"
        basearch: "x86_64"

  - name: "Red Hat Enterprise Linux 7 Server - Optional (RPMs)"
    product: "Red Hat Enterprise Linux Server"
    repository_list:
      - releasever: "7Server"
        basearch: "x86_64"

  - name: "Red Hat Enterprise Linux 7 Server - Supplementary (RPMs)"
    product: "Red Hat Enterprise Linux Server"
    repository_list:
      - releasever: "7Server"
        basearch: "x86_64"

# RHEL 7 Kickstart
  - name: "Red Hat Enterprise Linux 7 Server (Kickstart)"
    product: "Red Hat Enterprise Linux Server"
    repository_list:
      - releasever: "7.9"
        basearch: "x86_64"

  - name: "Red Hat Satellite Client 6 (for RHEL 7 Server) (RPMs)"
    product: "Red Hat Enterprise Linux Server"

  - name: "Red Hat Ansible Engine 2.9 RPMs for Red Hat Enterprise Linux 7 Server"
    product: "Red Hat Ansible Engine"

# RHEL 8.8 repos for LEAPP
  - name: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)"
    product: "Red Hat Enterprise Linux for x86_64"
    repository_list:
      - releasever: "8.8"
      - releasever: "8.10"

  - name: "Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)"
    product: "Red Hat Enterprise Linux for x86_64"
    repository_list:
      - releasever: "8.8"
      - releasever: "8.10"

  - name: "Red Hat Enterprise Linux 8 for x86_64 - Supplementary (RPMs)"
    product: "Red Hat Enterprise Linux for x86_64"
    repository_list:
      - releasever: "8.8"
      - releasever: "8.10"

# RHEL9.2 repos for LEAPP_8_2_9
  - name: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS (RPMs)"
    product: "Red Hat Enterprise Linux for x86_64"
    repository_list:
      - releasever: "9.2"
      - releasever: "9.4"

  - name: "Red Hat Enterprise Linux 9 for x86_64 - AppStream (RPMs)"
    product: "Red Hat Enterprise Linux for x86_64"
    repository_list:
      - releasever: "9.2"
      - releasever: "9.4"

  - name: "Red Hat Enterprise Linux 9 for x86_64 - Supplementary (RPMs)"
    product: "Red Hat Enterprise Linux for x86_64"
    repository_list:
      - releasever: "9.2"
      - releasever: "9.4"

# RHEL9_aarch64 kickstart repos
  - name: "Red Hat Enterprise Linux 9 for ARM 64 - BaseOS (Kickstart)"
    product: "Red Hat Enterprise Linux for ARM 64"
    repository_list:
      - releasever: "9.2"
      - releasever: "9.4"

  - name: "Red Hat Enterprise Linux 9 for ARM 64 - AppStream (Kickstart)"
    product: "Red Hat Enterprise Linux for ARM 64"
    repository_list:
      - releasever: "9.2"
      - releasever: "9.4"

# RHEL9_aarch64 repos
  - name: "Red Hat Enterprise Linux 9 for ARM 64 - BaseOS (RPMs)"
    product: "Red Hat Enterprise Linux for ARM 64"
    repository_list:
      - releasever: "9"

  - name: "Red Hat Enterprise Linux 9 for ARM 64 - AppStream (RPMs)"
    product: "Red Hat Enterprise Linux for ARM 64"
    repository_list:
      - releasever: "9"

  - name: "Red Hat Enterprise Linux 9 for ARM 64 - Supplementary (RPMs)"
    product: "Red Hat Enterprise Linux for ARM 64"
    repository_list:
      - releasever: "9"

  - name: "Red Hat Satellite Client 6 for RHEL 9 aarch64 (RPMs)"
    product: "Red Hat Enterprise Linux for ARM 64"

# RHEL8 and RHEL9 HA Repos
  - name: "Red Hat Enterprise Linux 8 for x86_64 - High Availability (RPMs)"
    product: "Red Hat Enterprise Linux High Availability for x86_64"
    repository_list:
      - releasever: "8"

  - name: "Red Hat Enterprise Linux 9 for x86_64 - High Availability (RPMs)"
    product: "Red Hat Enterprise Linux High Availability for x86_64"
    repository_list:
      - releasever: "9"
