---
# This play will configure the rhisam Content Views for the lab.
# Create requires the ccv loop variable.
- name: Creating the specified content views
  include_tasks: create_ccv.yml
  loop: "{{ ccvs_user }}"
  loop_control:
    loop_var: ccv
  when: "ccvs_user is defined"
  tags:
    - tags_content_management
    - tags_composite_content_views
    - tags_user
    - tags_user_composite_content_views

# Publish requires the cv loop variable. 
- name: Publish the specified content views
  include_tasks: publish_cv_version.yml
  loop: "{{ ccvs_user }}"
  loop_control:
    loop_var: cv
  when: "ccvs_user is defined"
  tags:
    - tags_content_management
    - tags_composite_content_views
    - tags_user
    - tags_user_composite_content_views
