---
# This play creates an individual content view from specified paramters
- name: "Ensure the state of content view - {{ content_view.name }}"
  redhat.satellite.content_view:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_url }}"
    organization: "{{ satellite_organization }}"
    validate_certs: "{{ satellite_validate_certs }}"
    name: "{{ content_view.name }}"
    description: "{{ content_view.desc }}"
    repositories: "{{ content_view.repositories }}"
    state: "{{ content_view.state | default(omit) }}"

# Add the filters
- name: "Configure the filters for the Content View - {{ content_view.name }}"
  when: "content_view.filters is defined"
  ansible.builtin.include_tasks: "create_cv_filter.yml"
  loop: "{{ content_view.filters }}"
  loop_control:
    loop_var: content_view_filter
  no_log: true
