---

# This determines if we should publish a content view version
# based on whether
#    skip_publish_all has been set to true
#    the content view has been published within cv.publication_threshold_hours
#    the content view has been set to force_publish
# It expects to be called in a loop with a loop variable cv

- name: "Ensure content meets publication requirements"
  ansible.builtin.set_fact:
    publish_content: false                       # default to false - only publish when necessary
    hours_since_publication: 8766                # assume the last publication was long ago.. one year - 365.25 days
    exceeded_publication_threshold_hours: false  # assume we haven't exceeded the threshold

- name: "Get content view info: {{ content_view.name }}"
  redhat.satellite.content_view_info:
    username: "{{ satellite_username | default(omit) }}"
    password: "{{ satellite_password | default(omit) }}"
    use_gssapi: "{{ satellite_use_gssapi | default(omit) }}"
    server_url: "{{ satellite_url }}"
    organization: "{{ satellite_organization }}"
    validate_certs: "{{ satellite_validate_certs }}"
    name: "{{ content_view.name }}"
  register: cv_info
  changed_when: false

# Satellite returns the time for these values in UTC
- name: "Determine hours since last publication time"
  when: cv_info.content_view.last_published
  ansible.builtin.set_fact:
    hours_since_publication: "{{ (now(utc=true) - (cv_info.content_view.last_published[:-4] | to_datetime)).seconds / 3600 | float }}"

- name: "Print hours since last publication"
  ansible.builtin.debug:
    var: hours_since_publication

- name: "Determine if we have exceeded publication threshold hours"
  when:
    - content_view.publication_threshold_hours is defined
    - (hours_since_publication|float) > (content_view.publication_threshold_hours|float)
  ansible.builtin.set_fact:
    exceeded_publication_threshold_hours: true

- name: "If we have exceeded the threshold and skip_publish_all is false, Publish"
  when:
    - exceeded_publication_threshold_hours
    - not skip_publish_all
  ansible.builtin.set_fact:
    publish_content: true

- name: "If we been asked to force publish *this* content view, Publish"
  when: (content_view.force_publish is defined and content_view.force_publish)
  ansible.builtin.set_fact:
    publish_content: true

- name: "Publishing content view - {{ content_view.name }}"
  when: publish_content
  redhat.satellite.content_view_version:
    username: "{{ satellite_username | default(omit) }}"
    password: "{{ satellite_password | default(omit) }}"
    use_gssapi: "{{ satellite_use_gssapi | default(omit) }}"
    server_url: "{{ satellite_url }}"
    organization: "{{ satellite_organization }}"
    validate_certs: "{{ satellite_validate_certs }}"
    content_view: "{{ content_view.name }}"
    description: "{{ content_view.description | default(omit) }}"
    version: "{{ content_view.version | default(omit) }}" # default is a new version
    lifecycle_environments: "{{ content_view.environments | default(omit) }}" # underlying default is publish new version to the library
    state: "{{ content_view.state | default(omit) }}" # underlying default is present
  async: "{{ cv_publish_timeout | default(14400) }}"
  poll: "{{ cv_publish_retry_interval | default(15) }}"
