---

- name: "Ensure the configuration of SCAP content"
  when: scap_contents is defined and (scap_contents | length) > 0
  ansible.builtin.include_tasks: "ensure_scap_content.yml"
  loop: "{{ scap_contents }}"
  loop_control:
    loop_var: scap_content
  no_log: true
  tags:
    - tags_rhisam
    - tags_scap_config
    - tags_scap_contents
