---

- name: "Set the default resource type"
  ansible.builtin.set_fact:
    resource_type: "{{ resource_search_type | default('repository_sets') }}"

- name: "Find repository set by label."
  redhat.satellite.resource_info:
    username: "{{ satellite_username | default(omit) }}"
    password: "{{ satellite_password | default(omit) }}"
    use_gssapi: "{{ satellite_use_gssapi | default(omit) }}"
    server_url: "{{ satellite_url }}"
    organization: "{{ satellite_organization }}"
    validate_certs: "{{ satellite_validate_certs }}"
    resource: "{{ resource_type }}"  # e.g. repository_sets
    search: '{{ resource_search_query }}' # e.g. "name ~ "Red Hat Satellite Client 6""
    full_details: true
  register: resource_result

- name: "Log resourse info"
  ansible.builtin.debug:
    var: resourc_result

- name: "Dig into the results"
  when: resource_type == "repository_sets"
  ansible.builtin.debug:
    var: item
  loop: "{{ result | community.general.json_query(query) }}"
  vars:
    query: "repository_sets[*].{product: product.name, name: name, label: label}"
