---
# Configure the rhisam and user compute profiles

- name: "Configure the compute profiles"
  when: compute_profiles is defined and (compute_profiles | length) > 0
  ansible.builtin.include_tasks: "ensure_compute_profile.yml"
  loop: "{{ compute_profiles }}"
  loop_control:
    loop_var: compute_profile
  no_log: true
  tags:
    - tags_rhisam
    - tags_provisioning_config
    - tags_compute_profiles
