---

- name: "Assign Host Location and Organization"
  redhat.satellite.host:
    username: "{{ satellite_username | default(omit) }}"
    password: "{{ satellite_password | default(omit) }}"
    use_gssapi: "{{ satellite_use_gssapi | default(omit) }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_validate_certs }}"
    state: "{{ capsule.state | default(omit) }}"
    name: "{{ capsule.fqdn }}"
    organization: "{{ capsule.organization }}"
    location: "{{ capsule.location }}"
