- name: "Ensure state of the subscription manifest"
  redhat.satellite.subscription_manifest:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_validate_certs }}"
    organization: "{{ subscription_manifest.organization }}"
    manifest_path: "{{ subscription_manifest.path | default(omit) }}"
    repository_url: "{{ subscription_manifest.repository_url | default(omit) }}"
    state: "{{ subscription_manifest.state | default('refreshed') }}"
