---
# Configure the rhisam and user identity management or AD realms

- name: "Ensure the configuration for realms"
  when: "satellite_realms is defined"
  ansible.builtin.include_tasks: "ensure_realm.yml"
  loop: "{{ satellite_realms }}"
  loop_control:
    loop_var: satellite_realm
  no_log: true
  tags:
    - tags_rhisam
    - tags_provisioning_config
    - tags_satellite_realms
