---

- name: "Configure rhisam virtwho configurations"
  ansible.builtin.include_tasks: "ensure_virtwho_config.yml"
  loop: "{{ virtwho_configs_rhisam }}"
  loop_control:
    loop_var: "virtwho_config"
  when: "virtwho_configs_rhisam is defined"
  tags:
    - tags_rhisam
    - tags_content_management_config
    - tags_virtwho_configs
    - tags_virtwho_configs_rhisam

- name: "Configure user virtwho configurations"
  ansible.builtin.include_tasks: "ensure_virtwho_config.yml"
  loop: "{{ virtwho_configs_user }}"
  loop_control:
    loop_var: "virtwho_config"
  when: "virtwho_configs_user is defined"
  tags:
    - tags_user
    - tags_content_management_config
    - tags_virtwho_configs
    - tags_virtwho_configs_user
