---
#  Add the repository to the custom product
#  state defaults to present

- name: "Ensure the state of repository - {{ custom_product_repository.name }}"
  redhat.satellite.repository:
    username: "{{ satellite_username | default(omit) }}"
    password: "{{ satellite_password | default(omit) }}"
    use_gssapi: "{{ satellite_use_gssapi | default(omit) }}"
    server_url: "{{ satellite_url }}"
    organization: "{{ satellite_organization }}"
    name: "{{ custom_product_repository.name }}"
    state: "{{ custom_product_repository.state | default(omit) }}"
    product: "{{ custom_product.name }}"
    content_type: "{{ custom_product_repository.content_type }}"

    validate_certs: "{{ satellite_validate_certs | default(omit) }}"
    ansible_collection_requirements: "{{ custom_product_repository.ansible_collection_requirements | default(omit) }}"
    arch: "{{ custom_product_repository.arch | default(omit) }}"
    auto_enabled: "{{ custom_product_repository.auto_enabled | default(omit) }}"
    ca_path: "{{ custom_product_repository.ca_path | default(omit) }}"
    checksum_type: "{{ custom_product_repository.checksum_type | default(omit) }}"
    deb_architectures: "{{ custom_product_repository.deb_architectures | default(omit) }}"
    deb_components: "{{ custom_product_repository.deb_components | default(omit) }}"
    deb_errata_url: "{{ custom_product_repository.deb_errata_url | default(omit) }}"
    deb_releases: "{{ custom_product_repository.deb_releases | default(omit) }}"
    description: "{{ custom_product_repository.description | default(omit) }}"
    docker_tags_whitelist: "{{ custom_product_repository.docker_tags_whitelist | default(omit) }}"
    docker_upstream_name: "{{ custom_product_repository.docker_upstream_name | default(omit) }}"
    download_concurrency: "{{ custom_product_repository.download_concurrency | default(omit) }}"
    download_policy: "{{ custom_product_repository.download_policy | default(omit) }}"
    exclude_tags: "{{ custom_product_repository.exclude_tags | default(omit) }}"
    gpg_key: "{{ custom_product_repository.gpg_key | default(omit) }}"
    http_proxy: "{{ custom_product_repository.http_proxy | default(omit) }}"
    http_proxy_policy: "{{ custom_product_repository.http_proxy_policy | default(omit) }}"
    ignorable_content: "{{ ignorable_content | default(omit) }}"
    include_tags: "{{ custom_product_repository.include_tags | default(omit) }}"
    label: "{{ custom_product_repository.label | default(omit) }}"
    mirror_on_sync: "{{ custom_product_repository.mirror_on_sync | default(omit) }}"
    mirroring_policy: "{{ custom_product_repository.mirroring_policy | default(omit) }}"
    os_versions: "{{ custom_product_repository.os_versions | default(omit) }}"
    ssl_ca_cert: "{{ custom_product_repository.ssl_ca_cert | default(omit) }}"
    ssl_client_cert: "{{ custom_product_repository.ssl_client_cert | default(omit) }}"
    ssl_client_key: "{{ custom_product_repository.ssl_client_key | default(omit) }}"
    unprotected: "{{ custom_product_repository.unprotected | default(omit) }}"
    upstream_password: "{{ custom_product_repository.upstream_password | default(omit) }}"
    upstream_username: "{{ custom_product_repository.upstream_username | default(omit) }}"
    url: "{{ custom_product_repository.url | default(omit) }}"
    verify_ssl_on_sync: "{{ custom_product_repository.verify_ssl_on_sync | default(omit) }}"
