---

- name: "Ensure the location configuration"
  redhat.satellite.location:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_validate_certs }}"
    state: "{{ location.state | default(omit) }}"
    description: "{{ location.description | default(omit) }}"
    name: "{{ location.name }}"
    organizations: "{{ location.organizations | default('[]') }}"
    parameters: "{{ location.parameters | default('[]') }}"
    parent: "{{ location.parent | default(omit) }}"
