---

- name: "Ensure the location configuration"
  redhat.satellite.location:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_validate_certs }}"
    state: "{{ satellite_location.state | default(omit) }}"
    description: "{{ satellite_location.description | default(omit) }}"
    name: "{{ satellite_location.name }}"
    organizations: "{{ satellite_location.organizations | default('[]') }}"
    parameters: "{{ satellite_location.parameters | default('[]') }}"
    parent: "{{ satellite_location.parent | default(omit) }}"
