---

# This play will create the POC specific usergroups in Satellite
# and map them to our external IdM groups.

- name: "Create an external user group"
  redhat.satellite.external_usergroup:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_validate_certs | default(omit) }}" # drop through to the module default (true)
    name: "{{ user_group_external.auth_source_group_name }}"
    auth_source: "{{ user_group_external.auth_source }}"
    usergroup: "{{ user_group_external.sat_usergroup }}"
    state: "{{ user_group_external.state | default(omit) }}" # drop through to the module default (present)
