---

- name: "Ensure the external user groups for the configuration"
  when: satellite_user_groups_external is defined and (satellite_user_groups_external | length) > 0
  ansible.builtin.include_tasks: "ensure_user_group_external.yml"
  loop: "{{ satellite_user_groups_external }}"
  loop_control:
    loop_var: satellite_user_group_external
  no_log: true
  tags:
    - tags_rhisam
    - tags_satellite_management_config
    - tags_satellite_user_groups_external
