---
# compute_profiles
# yamllint disable rule:line-length

vmware_cluster1_name: "chassis3"
vmware_cluster1_path: "/Datacenters/example.ca/vm"
vmware_cluster1_datastore: "NASAEX_VMS"
vmware_cluster1_network: "VM Network"

compute_profiles:
  - name: "SOE_Small"
    compute_attributes:
      - compute_resource: "VMware_Lab"
        vm_attrs:
          cpus: 1
          corespersocket: 1
          memory_mb: 4096
          cluster: "{{ vmware_cluster1_name }}"
          # resource_pool: "Resources"
          path: "{{ vmware_cluster1_path }}"
          guest_id: "rhel8_64Guest"
          hardware_version: "Default"
          memoryHotAddEnabled: true
          cpuHotAddEnabled: true
          add_cdrom: false
          boot_order:
            - "network"
            - "disk"
          scsi_controllers:
            - type: ParaVirtualSCSIController
              key: 1000
          volumes_attributes:
            0:
              thin: true
              name: "Hard disk"
              mode: "persistent"
              controller_key: 1000
              datastore: "{{ vmware_cluster1_datastore }}"
              size_gb: 65
          interfaces_attributes:
            0:
              type: "VirtualVmxnet3"
              network: "{{ vmware_cluster1_network }}"
      - compute_resource: "Azure_Lab"
        vm_attrs:
          resource_group: "rg_example_ca"
          vm_size: "Standard_B2ms"
          platform: "Linux"
          username: "realm-capsule"
          password: "{{ satellite_admin_password }}"
          ssh_key_data: "{{ azure1_user_ssh_key }}"
          premium_os_disk: "false"
          os_disk_size_gb: "80"
          os_disk_caching: ""
          script_command: ""
          script_uris: ""
          tags: ""
          nvidia_gpu_extension: "false"
          interfaces_attributes:
            0:
              network: "/subscriptions/{{ azure1_subscription_id_vault }}/resourceGroups/rg_example_ca/providers/Microsoft.Network/virtualNetworks/az_example_ca_vnet/subnets/az_example_ca_subnet"
              public_ip: "None"
              private_ip: "true"
          volumes_attributes:
            0:
              disk_size_gb: "10"
              data_disk_caching: ""

  - name: "SOE_Medium"
    compute_attributes:
      - compute_resource: "VMware_Lab"
        vm_attrs:
          cpus: 1
          corespersocket: 1
          memory_mb: 8192
          cluster: "{{ vmware_cluster1_name }}"
          # resource_pool: "Resources"
          path: "{{ vmware_cluster1_path }}"
          guest_id: "rhel8_64Guest"
          hardware_version: "Default"
          memoryHotAddEnabled: true
          cpuHotAddEnabled: true
          add_cdrom: false
          boot_order:
            - "network"
            - "disk"
          scsi_controllers:
            - type: ParaVirtualSCSIController
              key: 1000
          volumes_attributes:
            0:
              thin: true
              name: "Hard disk"
              mode: "persistent"
              controller_key: 1000
              datastore: "{{ vmware_cluster1_datastore }}"
              size_gb: 100
          interfaces_attributes:
            0:
              type: "VirtualVmxnet3"
              network: "{{ vmware_cluster1_network }}"
      - compute_resource: "Azure_Lab"
        vm_attrs:
          resource_group: "rg_example_ca"
          vm_size: "Standard_B4ms"
          platform: "Linux"
          username: "realm-capsule"
          password: "{{ satellite_admin_password }}"
          ssh_key_data: "{{ azure1_user_ssh_key }}"
          premium_os_disk: "false"
          os_disk_size_gb: "80"
          os_disk_caching: ""
          script_command: ""
          script_uris: ""
          tags: ""
          nvidia_gpu_extension: "false"
          interfaces_attributes:
            0:
              network: "/subscriptions/{{ azure1_subscription_id_vault }}/resourceGroups/rg_example_ca/providers/Microsoft.Network/virtualNetworks/az_example_ca_vnet/subnets/az_example_ca_subnet"
              public_ip: "None"
              private_ip: "true"
          volumes_attributes:
            0:
              disk_size_gb: "50"
              data_disk_caching: ""

  - name: "SOE_Large"
    compute_attributes:
      - compute_resource: "VMware_Lab"
        vm_attrs:
          cpus: 2
          corespersocket: 1
          memory_mb: 16364
          cluster: "{{ vmware_cluster1_name }}"
          # resource_pool: "Resources"
          path: "{{ vmware_cluster1_path }}"
          guest_id: "rhel8_64Guest"
          hardware_version: "Default"
          memoryHotAddEnabled: true
          cpuHotAddEnabled: true
          add_cdrom: false
          boot_order:
            - "network"
            - "disk"
          scsi_controllers:
            - type: ParaVirtualSCSIController
              key: 1000
          volumes_attributes:
            0:
              thin: true
              name: "Hard disk"
              mode: "persistent"
              controller_key: 1000
              datastore: "{{ vmware_cluster1_datastore }}"
              size_gb: 100
          interfaces_attributes:
            0:
              type: "VirtualVmxnet3"
              network: "{{ vmware_cluster1_network }}"
      - compute_resource: "Azure_Lab"
        vm_attrs:
          resource_group: "rg_example_ca"
          vm_size: "Standard_B8ms"
          platform: "Linux"
          username: "realm-capsule"
          password: "{{ satellite_admin_password }}"
          ssh_key_data: "{{ azure1_user_ssh_key }}"
          premium_os_disk: "false"
          os_disk_size_gb: "80"
          os_disk_caching: ""
          script_command: ""
          script_uris: ""
          tags: ""
          nvidia_gpu_extension: "false"
          interfaces_attributes:
            0:
              network: "/subscriptions/{{ azure1_subscription_id_vault }}/resourceGroups/rg_example_ca/providers/Microsoft.Network/virtualNetworks/az_example_ca_vnet/subnets/az_example_ca_subnet"
              public_ip: "None"
              private_ip: "true"
          volumes_attributes:
            0:
              disk_size_gb: "100"
              data_disk_caching: ""
            1:
              disk_size_gb: "100"
              data_disk_caching: ""
