---

# Content credentials for non-Red Hat products
content_credentials:
  - name: "RedHatGPG"
    content_type: "gpg_key"
    content: "{{ lookup('file', '/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release') }}"
    state: "present"
  - name: "RedHatSSL"
    content_type: "cert"
    content: "{{ lookup('url', 'https://ftp.redhat.com/redhat/convert2rhel/redhat-uep.pem') | replace(',','\n')}}"
    state: "present"
  - name: "CentOS9OfficialGPG"
    content_type: "gpg_key"
    content: "{{ lookup('url', 'https://www.centos.org/keys/RPM-GPG-KEY-CentOS-Official-SHA256') }}"
    state: "present"
  - name: "CentOS7GPG"
    content_type: "gpg_key"
    content: "{{ lookup('url', 'https://yum.oracle.com/RPM-GPG-KEY-oracle-ol7') }}"
    state: "present"
  - name: "OracleLinux7GPG"
    content_type: "gpg_key"
    content: "{{ lookup('url', 'https://vault.centos.org/7.9.2009/os/x86_64/RPM-GPG-KEY-CentOS-7') }}"
    state: "present"
