---
# Tell the YAML linter to ignore long lines
# yamllint disable rule:line-length

# Where we have full kickstart trees, we sync them and include them in the content view
# This is an example of web based media.
# a server installing with this media needs internet access to the specified path/url

media:
  - name: "CentOS 7 mirror"
    os_family: "Redhat"
    path: "http://vault.centos.org/7.9.2009/os/x86_64/"
    organization: "{{ satellite_organization }}"
    location: "{{ satellite_location }}"
