---

# For all of our Red Hat Products and Custom products,
# the repositories are created along with the repository set or custom product

# In day 0 operations, we use this to Override download_policy defaults, set content_credentials, etc.. as an example
# In day 2 operations, we can use this to add and remove repos from our products.

# The following are some examples.
# For custom products we can set these via the product definition as well

satellite_repositories:
  - name: "Red Hat Enterprise Linux 10 for x86_64 - AppStream Kickstart 10.0"
    product: "Red Hat Enterprise Linux for x86_64"
    content_type: "yum"
    download_policy: "immediate"
  - name: "Red Hat Enterprise Linux 10 for x86_64 - AppStream RPMs 10"
    product: "Red Hat Enterprise Linux for x86_64"
    content_type: "yum"
    download_policy: "immediate"
  - name: "Red Hat Enterprise Linux 10 for x86_64 - BaseOS Kickstart 10.0"
    product: "Red Hat Enterprise Linux for x86_64"
    content_type: "yum"
    download_policy: "immediate"
  - name: "Red Hat Enterprise Linux 10 for x86_64 - BaseOS RPMs 10"
    product: "Red Hat Enterprise Linux for x86_64"
    content_type: "yum"
    download_policy: "immediate"
  - name: "Red Hat Satellite Client 6 for RHEL 10 x86_64 RPMs"
    product: "Red Hat Enterprise Linux for x86_64"
    content_type: "yum"
    download_policy: "immediate"
  - name: "Red Hat Satellite 6 Client 2 for RHEL 10 x86_64 RPMs"
    product: "Red Hat Enterprise Linux for x86_64"
    content_type: "yum"
    download_policy: "immediate"

  - name: "Red Hat Enterprise Linux 10 for ARM 64 - AppStream Kickstart 10.0"
    product: "Red Hat Enterprise Linux for ARM 64"
    content_type: "yum"
    download_policy: "immediate"
  - name: "Red Hat Enterprise Linux 10 for ARM 64 - AppStream RPMs 10"
    product: "Red Hat Enterprise Linux for ARM 64"
    content_type: "yum"
    download_policy: "immediate"
  - name: "Red Hat Enterprise Linux 10 for ARM 64 - BaseOS Kickstart 10.0"
    product: "Red Hat Enterprise Linux for ARM 64"
    content_type: "yum"
    download_policy: "immediate"
  - name: "Red Hat Enterprise Linux 10 for ARM 64 - BaseOS RPMs 10"
    product: "Red Hat Enterprise Linux for ARM 64"
    content_type: "yum"
    download_policy: "immediate"
  - name: "Red Hat Satellite Client 6 for RHEL 10 aarch64 RPMs"
    product: "Red Hat Enterprise Linux for ARM 64"
    content_type: "yum"
    download_policy: "immediate"
  - name: "Red Hat Satellite 6 Client 2 for RHEL 10 aarch64 RPMs"
    product: "Red Hat Enterprise Linux for ARM 64"
    content_type: "yum"
    download_policy: "immediate"

  - name: "Red Hat Enterprise Linux 9 for x86_64 - AppStream Kickstart 9.6"
    product: "Red Hat Enterprise Linux for x86_64"
    content_type: "yum"
    download_policy: "immediate"
  - name: "Red Hat Enterprise Linux 9 for x86_64 - AppStream Kickstart 9.5"
    product: "Red Hat Enterprise Linux for x86_64"
    content_type: "yum"
    download_policy: "immediate"
  - name: "Red Hat Enterprise Linux 9 for x86_64 - AppStream RPMs 9"
    product: "Red Hat Enterprise Linux for x86_64"
    content_type: "yum"
    download_policy: "immediate"
  - name: "Red Hat Enterprise Linux 9 for x86_64 - AppStream RPMs 9.6"
    product: "Red Hat Enterprise Linux for x86_64"
    content_type: "yum"
    download_policy: "immediate"
  - name: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS Kickstart 9.6"
    product: "Red Hat Enterprise Linux for x86_64"
    content_type: "yum"
    download_policy: "immediate"
  - name: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS Kickstart 9.5"
    product: "Red Hat Enterprise Linux for x86_64"
    content_type: "yum"
    download_policy: "immediate"
  - name: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS RPMs 9"
    product: "Red Hat Enterprise Linux for x86_64"
    content_type: "yum"
    download_policy: "immediate"
  - name: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS RPMs 9.6"
    product: "Red Hat Enterprise Linux for x86_64"
    content_type: "yum"
    download_policy: "immediate"
  - name: "Red Hat Satellite Client 6 for RHEL 9 x86_64 RPMs"
    product: "Red Hat Enterprise Linux for x86_64"
    content_type: "yum"
    download_policy: "immediate"
  - name: "Red Hat Satellite 6 Client 2 for RHEL 9 x86_64 RPMs"
    product: "Red Hat Enterprise Linux for x86_64"
    content_type: "yum"
    download_policy: "immediate"

  - name: "Red Hat Enterprise Linux 9 for ARM 64 - AppStream Kickstart 9.6"
    product: "Red Hat Enterprise Linux for ARM 64"
    content_type: "yum"
    download_policy: "immediate"
  - name: "Red Hat Enterprise Linux 9 for ARM 64 - AppStream RPMs 9"
    product: "Red Hat Enterprise Linux for ARM 64"
    content_type: "yum"
    download_policy: "immediate"
  - name: "Red Hat Enterprise Linux 9 for ARM 64 - BaseOS Kickstart 9.6"
    product: "Red Hat Enterprise Linux for ARM 64"
    content_type: "yum"
    download_policy: "immediate"
  - name: "Red Hat Enterprise Linux 9 for ARM 64 - BaseOS RPMs 9"
    product: "Red Hat Enterprise Linux for ARM 64"
    content_type: "yum"
    download_policy: "immediate"
  - name: "Red Hat Satellite Client 6 for RHEL 9 aarch64 RPMs"
    product: "Red Hat Enterprise Linux for ARM 64"
    content_type: "yum"
    download_policy: "immediate"
  - name: "Red Hat Satellite 6 Client 2 for RHEL 9 aarch64 RPMs"
    product: "Red Hat Enterprise Linux for ARM 64"
    content_type: "yum"
    download_policy: "immediate"

  - name: "Red Hat Enterprise Linux 8 for x86_64 - AppStream Kickstart 8.10"
    product: "Red Hat Enterprise Linux for x86_64"
    content_type: "yum"
    download_policy: "immediate"
  - name: "Red Hat Enterprise Linux 8 for x86_64 - AppStream RPMs 8"
    product: "Red Hat Enterprise Linux for x86_64"
    content_type: "yum"
    download_policy: "immediate"
  - name: "Red Hat Enterprise Linux 8 for x86_64 - AppStream RPMs 8.10"
    product: "Red Hat Enterprise Linux for x86_64"
    content_type: "yum"
    download_policy: "immediate"
  - name: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.10"
    product: "Red Hat Enterprise Linux for x86_64"
    content_type: "yum"
    download_policy: "immediate"
  - name: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS RPMs 8"
    product: "Red Hat Enterprise Linux for x86_64"
    content_type: "yum"
    download_policy: "immediate"
  - name: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS RPMs 8.10"
    product: "Red Hat Enterprise Linux for x86_64"
    content_type: "yum"
    download_policy: "immediate"
  - name: "Red Hat Satellite Client 6 for RHEL 8 x86_64 RPMs"
    product: "Red Hat Enterprise Linux for x86_64"
    content_type: "yum"
    download_policy: "immediate"

  - name: "Red Hat Satellite Maintenance 6.17 for RHEL 9 x86_64 RPMs"
    product: "Red Hat Enterprise Linux for x86_64"
    content_type: "yum"
    download_policy: "immediate"

  - name: "Red Hat Satellite Capsule 6.17 for RHEL 9 x86_64 RPMs"
    product: "Red Hat Satellite Capsule"
    content_type: "yum"
    download_policy: "immediate"

  - name: "Red Hat Ansible Automation Platform 2.4 for RHEL 9 x86_64 Files"
    product: "Red Hat Ansible Automation Platform"
    content_type: "file"
    download_policy: "on_demand"

  - name: "Red Hat Ansible Automation Platform 2.5 for RHEL 9 x86_64 Files"
    product: "Red Hat Ansible Automation Platform"
    content_type: "file"
    download_policy: "immediate"

  - name: "convert2rhel7"
    product: "convert2rhel"
    content_type: "yum"
    gpg_key: "RedHatGPG"
    ssl_ca_cert: "RedHatSSL"
    download_policy: "immediate"
    unprotected: false
  - name: "convert2rhel8"
    product: "convert2rhel"
    content_type: "yum"
    gpg_key: "RedHatGPG"
    ssl_ca_cert: "RedHatSSL"
    download_policy: "immediate"
    unprotected: false
  - name: "CentOS79"
    product: "CentOS79"
    content_type: "yum"
    gpg_key: "CentOS79GPG"
    download_policy: "immediate"
    unprotected: false
  - name: "updates"
    product: "CentOS79"
    content_type: "yum"
    gpg_key: "CentOS79GPG"
    download_policy: "immediate"
    unprotected: false
  - name: "centos-9-appstream"
    product: "CentOS Stream 9"
    content_type: "yum"
    gpg_key: "CentOS9OfficialGPG"
    download_policy: "on_demand"
    unprotected: false
  - name: "centos-9-baseos"
    product: "CentOS Stream 9"
    content_type: "yum"
    gpg_key: "CentOS9OfficialGPG"
    download_policy: "on_demand"
    unprotected: false
  - name: "OEL79"
    product: "OEL79"
    content_type: "yum"
    gpg_key: "OracleLinux7GPG"
    download_policy: "immediate"
    unprotected: false
