role_filters_all:
  - resource_type: "None"
    permissions:
      - "generate_ansible_inventory"
      - "import_ansible_playbooks"
      - "download_bootdisk"
      - "my_organizations"
      - "generate_foreman_rh_cloud"
      - "view_foreman_rh_cloud"
      - "dispatch_cloud_requests"
      - "control_organization_insights"
      - "access_dashboard"
      - "view_plugins"
      - "escalate_roles"
      - "view_statuses"
  - resource_type: "AnsibleRole"
    permissions:
      - "view_ansible_roles"
      - "destroy_ansible_roles"
      - "import_ansible_roles"
  - resource_type: "AnsibleVariable"
    permissions:
      - "view_ansible_variables"
      - "edit_ansible_variables"
      - "destroy_ansible_variables"
      - "create_ansible_variables"
      - "import_ansible_variables"
  - resource_type: "Architecture"
    permissions:
      - "view_architectures"
      - "create_architectures"
      - "edit_architectures"
      - "destroy_architectures"
  - resource_type: "Audit"
    permissions:
      - "view_audit_logs"
  - resource_type: "AuthSource"
    permissions:
      - "view_authenticators"
      - "create_authenticators"
      - "edit_authenticators"
      - "destroy_authenticators"
  - resource_type: "Bookmark"
    permissions:
      - "create_bookmarks"
      - "edit_bookmarks"
      - "destroy_bookmarks"
  - resource_type: "ComputeProfile"
    permissions:
      - "view_compute_profiles"
      - "create_compute_profiles"
      - "edit_compute_profiles"
      - "destroy_compute_profiles"
  - resource_type: "ComputeResource"
    permissions:
      - "view_compute_resources"
      - "create_compute_resources"
      - "edit_compute_resources"
      - "destroy_compute_resources"
      - "power_vm_compute_resources"
      - "destroy_vm_compute_resources"
      - "view_compute_resources_vms"
      - "create_compute_resources_vms"
      - "edit_compute_resources_vms"
      - "destroy_compute_resources_vms"
      - "power_compute_resources_vms"
      - "console_compute_resources_vms"
  - resource_type: "ConfigReport"
    permissions:
      - "view_config_reports"
      - "destroy_config_reports"
      - "upload_config_reports"
  - resource_type: "DiscoveryRule"
    permissions:
      - "view_discovery_rules"
      - "create_discovery_rules"
      - "edit_discovery_rules"
      - "execute_discovery_rules"
      - "destroy_discovery_rules"
  - resource_type: "Domain"
    permissions:
      - "view_domains"
      - "create_domains"
      - "edit_domains"
      - "destroy_domains"
  - resource_type: "ExternalUsergroup"  # Does not support granular filtering
    permissions:
      - "view_external_usergroups"
      - "create_external_usergroups"
      - "edit_external_usergroups"
      - "destroy_external_usergroups"
  - resource_type: "FactValue"
    permissions:
      - "view_facts"
      - "upload_facts"
  - resource_type: "Filter"
    permissions:
      - "view_filters"
      - "create_filters"
      - "edit_filters"
      - "destroy_filters"
  - resource_type: "ForemanOpenscap::ArfReport"
    permissions:
      - "view_arf_reports"
      - "destroy_arf_reports"
      - "create_arf_reports"
  - resource_type: "ForemanOpenscap::Policy"
    permissions:
      - "view_policies"
      - "edit_policies"
      - "create_policies"
      - "destroy_policies"
      - "assign_policies"
  - resource_type: "ForemanOpenscap::ScapContent"
    permissions:
      - "view_scap_contents"
      - "edit_scap_contents"
      - "create_scap_contents"
      - "destroy_scap_contents"
  - resource_type: "ForemanOpenscap::ScapTailoringFile"
    permissions:
      - "create_tailoring_files"
      - "view_tailoring_files"
      - "edit_tailoring_files"
      - "destroy_tailoring_files"
  - resource_type: "ForemanTasks::RecurringLogic"
    permissions:
      - "create_recurring_logics"
      - "view_recurring_logics"
      - "edit_recurring_logics"
  - resource_type: "ForemanTasks::Task"
    permissions:
      - "view_foreman_tasks"
      - "edit_foreman_tasks"
  - resource_type: "ForemanVirtWhoConfigure::Config"
    permissions:
      - "view_virt_who_config"
      - "create_virt_who_config"
      - "edit_virt_who_config"
      - "destroy_virt_who_config"
  - resource_type: "Host"
    permissions:
      - "cockpit_hosts"
      - "play_roles_on_host"
      - "view_hosts"
      - "edit_hosts"
      - "view_discovered_hosts"
      - "submit_discovered_hosts"
      - "auto_provision_discovered_hosts"
      - "provision_discovered_hosts"
      - "edit_discovered_hosts"
      - "destroy_discovered_hosts"
      - "create_hosts"
      - "destroy_hosts"
      - "build_hosts"
      - "power_hosts"
      - "console_hosts"
      - "ipmi_boot_hosts"
      - "forget_status_hosts"
  - resource_type: "Hostgroup"
    permissions:
      - "play_roles_on_hostgroup"
      - "view_hostgroups"
      - "edit_hostgroups"
      - "create_hostgroups"
      - "destroy_hostgroups"
  - resource_type: "HttpProxy"
    permissions:
      - "view_http_proxies"
      - "create_http_proxies"
      - "edit_http_proxies"
      - "destroy_http_proxies"
  - resource_type: "Image"
    permissions:
      - "view_images"
      - "create_images"
      - "edit_images"
      - "destroy_images"
  - resource_type: "InsightsHit"
    permissions:
      - "view_insights_hits"
  - resource_type: "JobInvocation"
    permissions:
      - "create_job_invocations"
      - "view_job_invocations"
      - "execute_jobs_on_infrastructure_hosts"
      - "cancel_job_invocations"
  - resource_type: "JobTemplate"
    permissions:
      - "view_job_templates"
      - "create_job_templates"
      - "edit_job_templates"
      - "destroy_job_templates"
      - "lock_job_templates"
  - resource_type: "Katello::ActivationKey"
    permissions:
      - "view_activation_keys"
      - "create_activation_keys"
      - "edit_activation_keys"
      - "destroy_activation_keys"
  - resource_type: "Katello::AlternateContentSource"
    permissions:
      - "view_alternate_content_sources"
      - "create_alternate_content_sources"
      - "edit_alternate_content_sources"
      - "destroy_alternate_content_sources"
  - resource_type: "Katello::ContentCredential"
    permissions:
      - "view_content_credentials"
      - "create_content_credentials"
      - "edit_content_credentials"
      - "destroy_content_credentials"
  - resource_type: "Katello::ContentView"
    permissions:
      - "view_content_views"
      - "create_content_views"
      - "edit_content_views"
      - "destroy_content_views"
      - "publish_content_views"
      - "promote_or_remove_content_views"
  - resource_type: "Katello::HostCollection"
    permissions:
      - "view_host_collections"
      - "create_host_collections"
      - "edit_host_collections"
      - "destroy_host_collections"
  - resource_type: "Katello::KTEnvironment"
    permissions:
      - "view_lifecycle_environments"
      - "create_lifecycle_environments"
      - "edit_lifecycle_environments"
      - "destroy_lifecycle_environments"
      - "promote_or_remove_content_views_to_environments"
  - resource_type: "Katello::Product"                       # Products and Repositories
    permissions:
      - "view_products"
      - "create_products"
      - "edit_products"
      - "destroy_products"
      - "sync_products"
  - resource_type: "Katello::Subscription"     # Does not support granular filtering
    permissions:
      - "view_subscriptions"
      - "attach_subscriptions"
      - "unattach_subscriptions"
      - "import_manifest"
      - "delete_manifest"
      - "manage_subscription_allocations"
  - resource_type: "Katello::SyncPlan"
    permissions:
      - "view_sync_plans"
      - "create_sync_plans"
      - "edit_sync_plans"
      - "destroy_sync_plans"
      - "sync_sync_plans"
  - resource_type: "KeyPair"
    permissions:
      - "view_keypairs"
      - "destroy_keypairs"
  - resource_type: "Location"
    permissions:
      - "view_locations"
      - "create_locations"
      - "edit_locations"
      - "destroy_locations"
      - "assign_locations"
  - resource_type: "LookupValue"
    permissions:
      - "view_lookup_values"
      - "create_lookup_values"
      - "edit_lookup_values"
      - "destroy_lookup_values"
  - resource_type: "MailNotification"
    permissions:
      - "view_mail_notifications"
      - "edit_user_mail_notifications"
  - resource_type: "Medium"
    permissions:
      - "view_media"
      - "create_media"
      - "edit_media"
      - "destroy_media"
  - resource_type: "Model"
    permissions:
      - "view_models"
      - "create_models"
      - "edit_models"
      - "destroy_models"
  - resource_type: "Operatingsystem"
    permissions:
      - "view_operatingsystems"
      - "create_operatingsystems"
      - "edit_operatingsystems"
      - "destroy_operatingsystems"
  - resource_type: "Organization"
    permissions:
      - "import_content"
      - "export_content"
      - "view_organizations"
      - "create_organizations"
      - "edit_organizations"
      - "destroy_organizations"
      - "assign_organizations"
  - resource_type: "Parameter"
    permissions:
      - "view_params"
      - "create_params"
      - "edit_params"
      - "destroy_params"
  - resource_type: "PersonalAccessToken"
    permissions:
      - "view_personal_access_tokens"
      - "create_personal_access_tokens"
      - "revoke_personal_access_tokens"
  - resource_type: "Ptable"
    permissions:
      - "view_ptables"
      - "create_ptables"
      - "edit_ptables"
      - "destroy_ptables"
      - "lock_ptables"
  - resource_type: "ProvisioningTemplate"
    permissions:
      - "view_provisioning_templates"
      - "create_provisioning_templates"
      - "edit_provisioning_templates"
      - "destroy_provisioning_templates"
      - "deploy_provisioning_templates"
      - "lock_provisioning_templates"
  - resource_type: "Realm"
    permissions:
      - "view_realms"
      - "create_realms"
      - "edit_realms"
      - "destroy_realms"
  - resource_type: "ReportTemplate"
    permissions:
      - "view_report_templates"
      - "create_report_templates"
      - "edit_report_templates"
      - "destroy_report_templates"
      - "lock_report_templates"
      - "generate_report_templates"
  - resource_type: "RemoteExecutionFeature"
    permissions:
      - "view_remote_execution_features"
      - "edit_remote_execution_features"
  - resource_type: "Role"
    permissions:
      - "view_roles"
      - "create_roles"
      - "edit_roles"
      - "destroy_roles"
  - resource_type: "Setting"
    permissions:
      - "view_settings"
      - "edit_settings"
  - resource_type: "SmartProxy"   # a.k.a. Capsule
    permissions:
      - "view_openscap_proxies"
      - "view_smart_proxies"
      - "manage_capsule_content"
      - "view_capsule_content"
      - "create_smart_proxies"
      - "edit_smart_proxies"
      - "destroy_smart_proxies"
      - "view_smart_proxies_autosign"
      - "create_smart_proxies_autosign"
      - "destroy_smart_proxies_autosign"
      - "view_smart_proxies_puppetca"
      - "edit_smart_proxies_puppetca"
      - "destroy_smart_proxies_puppetca"
  - resource_type: "SshKey"
    permissions:
      - "view_ssh_keys"
      - "create_ssh_keys"
      - "destroy_ssh_keys"
  - resource_type: "Subnet"
    permissions:
      - "view_subnets"
      - "create_subnets"
      - "edit_subnets"
      - "destroy_subnets"
      - "import_subnets"
  - resource_type: "Template"
    permissions:
      - "import_templates"
      - "export_templates"
      - "view_template_syncs"
  - resource_type: "TemplateInvocation"
    permissions:
      - "view_template_invocations"
      - "create_template_invocations"
      - "filter_autocompletion_for_template_invocation"
  - resource_type: "User"
    permissions:
      - "view_users"
      - "create_users"
      - "edit_users"
      - "destroy_users"
  - resource_type: "Usergroup"
    permissions:
      - "view_usergroups"
      - "create_usergroups"
      - "edit_usergroups"
      - "destroy_usergroups"
  - resource_type: "Webhook"
    permissions:
      - "view_webhooks"
      - "create_webhooks"
      - "edit_webhooks"
      - "destroy_webhooks"
  - resource_type: "WebhookTemplate"
    permissions:
      - "view_webhook_templates"
      - "create_webhook_templates"
      - "edit_webhook_templates"
      - "destroy_webhook_templates"
      - "lock_webhook_templates"
