---
# variables for a satellite installation

ipa_server_fqdn: "{{ ipa_server_fqdn }}"
foreman_proxy_realm_principal: "{{ foreman_proxy_realm_principal }}"

sat_installer_verbose: true
sat_installer_options:
  - '--skip-checks-i-know-better'
  - '--foreman-initial-organization "{{ satellite_initial_organization }}"'
  - '--foreman-initial-location "{{ satellite_initial_location }}"'
  - '--foreman-initial-admin-username "{{ satellite_admin_username }}"'
  - '--foreman-initial-admin-password "{{ satellite_admin_password }}"'
  - '--foreman-initial-admin-email "{{ satellite_admin_email }}"'
  - '--foreman-initial-admin-first-name  "Satellite"'
  - '--foreman-initial-admin-last-name  "Administrator"'
  - '--foreman-ipa-authentication true'
  - '--certs-server-ca-cert "/etc/ipa/ca.crt"'
  - '--certs-server-cert "/etc/ipa/private/{{ satellite_fqdn }}/{{ satellite_fqdn }}.crt"'
  - '--certs-server-key "/etc/ipa/private/{{ satellite_fqdn }}/{{ satellite_fqdn }}.key"'
  - '--enable-foreman-compute-ec2'
  - '--enable-foreman-compute-libvirt'
  - '--enable-foreman-compute-vmware'
  - '--foreman-proxy-dns true'
  - '--foreman-proxy-dns-managed false'
  - '--foreman-proxy-dns-provider "nsupdate_gss"'
  - '--foreman-proxy-dns-server "{{ ipa_server_fqdn }}"'
  - '--foreman-proxy-dns-tsig-keytab "/etc/foreman-proxy/freeipa.keytab"'
  - '--foreman-proxy-dns-tsig-principal "{{ foreman_proxy_realm_principal }}"'
  - '--foreman-proxy-http true'
  - '--foreman-proxy-realm true'
  - '--foreman-proxy-realm-keytab "/etc/foreman-proxy/freeipa.keytab"'
  - '--foreman-proxy-realm-principal "{{ foreman_proxy_realm_principal }}"'
  - '--foreman-proxy-realm-provider  "freeipa"'
  - '--foreman-proxy-registration true'
  - '--foreman-proxy-templates true'
  - '--foreman-proxy-tftp true'
  - '--foreman-proxy-content-enable-ansible true'
  - '--foreman-proxy-content-enable-deb true'
  - '--foreman-proxy-content-enable-docker true'
  - '--foreman-proxy-content-enable-file true'
  - '--foreman-proxy-content-enable-yum true'
  - '--foreman-proxy-plugin-discovery-install-images true'

#  Currently this must be false - no plugin shipped in repos
#  - '--foreman-proxy-content-enable-ostree false'
#  - '--foreman-proxy-content-enable-python true'

# when we are using Satellite as the dhcp server
#  - '--foreman-proxy-dhcp: false'
#  - '--foreman-proxy-dhcp-interface: "{{ ansible_facts.interfaces | select('match', '^(e)+') | list | first }}"'
#  - '--foreman-proxy-dhcp-range: "192.168.140.1 192.168.140.254"'
#  - '--foreman-proxy-dhcp-gateway: "192.168.140.1"'
#  - '--foreman-proxy-dhcp-nameservers: "192.168.140.10"'
#  - '--foreman-proxy-dhcp-option-domain: "[{{ satellite_domain }}]"'
#  - '--foreman-proxy-dhcp-pxeserver: "{{ satellite_fqdn }}"'
#  - '--foreman-proxy-dhcp-network: "192.168.140.0"'
#  - '--foreman-proxy-dhcp-netmask: "255.255.252.0"'

# when deploying Satellite < 6.15 add the following
#  - '--foreman-proxy-content-enable-katello-agent false'
