---
# Build a manifest from parameters or specify an existing manifest

manifest_name: "RedHatCanada"
manifest_path: "/root/bootstrap_manifest.zip"
manifest_portal_url: "https://subscription.rhsm.redhat.com"
manifest_validate_certs: true
manifest_cdn_username: "{{ cdn_username_vault }}"
manifest_cdn_password: "{{ cdn_password_vault }}"
manifest_account: "{{ cdn_account_number_vault }}"
manifest_subs: "{{ manifest_subs_vault }}"  # see rhisbuilder_vault_SAMPLE.yml
