---

settings_email:
  - name: "email_reply_address"
    full_name: "Email Reply Address"
    description: "Email reply address for emails that Satellite is sending"
    settings_type: "string"
    default: "satellite-noreply@example.ca"
    value: "satellite-noreply@example.ca"

  - name: "email_subject_prefix"
    full_name: "Email subject prefix"
    description: "Prefix to add to all outgoing email"
    settings_type: "string"
    default: "[satellite]"
    value: "[satellite.example.ca]"

  - name: "send_welcome_email"
    full_name: "Send welcome email"
    description: "Send a welcome email including username and URL to new users"
    settings_type: "boolean"
    default: "false"
    value: "false"

  - name: "delivery_method"
    full_name: "Delivery method"
    description: "Method used to deliver email"
    settings_type: "string"
    default: "Sendmail"
    value: "SMTP"

  - name: "smtp_enable_starttls_auto"
    full_name: "SMTP enable StartTLS auto"
    description: "SMTP automatic STARTTLS"
    settings_type: "boolean"
    default: "true"
    value: "true"

  - name: "smtp_openssl_verify_mode"
    full_name: "SMTP OpenSSL verify mode"
    description: "When using TLS, you can set how OpenSSL checks the certificate"
    settings_type: "string"
    default: "default"
    value: "default"

  - name: "smtp_address"
    full_name: "SMTP address"
    description: "SMTP address to connect to"
    settings_type: "string"
    default: "smtp.example.ca"
    value: "smtp.gmail.com"

  - name: "smtp_port"
    full_name: "SMTP port"
    description: "SMTP port to connect to"
    settings_type: "integer"
    default: 25
    value: 587

  - name: "smtp_domain"
    full_name: "SMTP HELO/EHLO domain"
    description: "HELO/EHLO domain"
    settings_type: "string"
    default: ""
    value: ""

  - name: "smtp_user_name"
    full_name: "SMTP username"
    description: "Username to use to authenticate, if required"
    settings_type: "string"
    default: "user@example.ca"
    value: "{{ satellite_smtp_user_name_vault }}"

  - name: "smtp_password"
    full_name: "SMTP password"
    description: "Password to use to authenticate, if required"
    settings_type: "string"
    encrypted: true
    default: "obfuscated_value"
    value: "{{ satellite_smtp_password_vault }}"

  - name: "smtp_authentication"
    full_name: "SMTP authentication"
    description: "Specify authentication type, if required"
    settings_type: "string"
    default: "none"
    value: "{{ satellite_smtp_authentication }}"

  - name: "sendmail_arguments"
    full_name: "Sendmail arguments"
    description: "Specify additional options to sendmail. Only used when the delivery method is set to sendmail."
    settings_type: "string"
    default: "-i"
    value: ""

  - name: "sendmail_location"
    full_name: "Sendmail location"
    description: "The location of the sendmail executable. Only used when the delivery method is set to sendmail."
    settings_type: "string"
    default: "/usr/sbin/sendmail"
    value: ""
