---
email_reply_address: "satellite-noreply@example.ca"
email_subject_prefix: "[satellite.example.ca]"
send_welcome_email: "false"
delivery_method: "SMTP"
smtp_enable_starttls_auto: "true"
smtp_openssl_verify_mode: "default"
smtp_address: "smtp.gmail.com"
smtp_port: 587
smtp_domain: ""
smtp_user_name: "{{ satellite_smtp_user_name_vault }}"
smtp_password: "{{ satellite_smtp_password_vault }}"
smtp_authentication: "{{ satellite_smtp_authentication }}"
sendmail_arguments: ""
sendmail_location: ""
