---

- name: "Ensure the satellite_subnet configuration"
  redhat.satellite.subnet:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_validate_certs }}"
    organizations: "{{ satellite_subnet.organizations }}"
    locations: "{{ satellite_subnet.locations }}"
    domains: "{{ satellite_subnet.domains | default(omit) }}"
    parameters: "{{ satellite_subnet.parameters | default(omit) }}"
    remote_execution_proxies: "{{ satellite_subnet.remote_execution_capsules | default(omit) }}"
    name: "{{ satellite_subnet.name }}"
    description: "{{ satellite_subnet.description | default(omit) }}"
    network_type: "{{ satellite_subnet.network_type | default(omit) }}"
    network: "{{ satellite_subnet.network }}"
    cidr: "{{ satellite_subnet.prefix | default(omit) }}"
    mask: "{{ satellite_subnet.mask | default(omit) }}"
    gateway: "{{ satellite_subnet.gateway | default(omit) }}"
    dns_primary: "{{ satellite_subnet.dns_primary | default(omit) }}"
    dns_secondary: "{{ satellite_subnet.dns_secondary | default(omit) }}"
    ipam: "{{ satellite_subnet.ipam | default(omit) }}"
    externalipam_group: "{{ satellite_subnet.externalipam_group | default(omit) }}"
    from_ip: "{{ satellite_subnet.from_ip | default(omit) }}"
    to_ip: "{{ satellite_subnet.to_ip | default(omit) }}"
    vlanid: "{{ satellite_subnet.vlanid | default(omit) }}"
    mtu: "{{ satellite_subnet.mtu | default(omit) }}"
    boot_mode: "{{ satellite_subnet.boot_mode | default(omit) }}"
    bmc_proxy: "{{ satellite_subnet.bmc_capsule | default(omit) }}"
    dhcp_proxy: "{{ satellite_subnet.dhcp_capsule | default(omit) }}"
    discovery_proxy: "{{ satellite_subnet.discovery_capsule | default(omit) }}"
    dns_proxy: "{{ satellite_subnet.dns_capsule | default(omit) }}"
    externalipam_proxy: "{{ satellite_subnet.externalipam_capsule | default(omit) }}"
    httpboot_proxy: "{{ satellite_subnet.httpboot_capsule | default(omit) }}"
    template_proxy: "{{ satellite_subnet.template_capsule | default(omit) }}"
    tftp_proxy: "{{ satellite_subnet.tftp_capsule | default(omit) }}"
    state: "{{ satellite_subnet.state | default(omit) }}"
