---
# By the time you read this, you probably understand the pattern

- name: "Ensure the configuration the satellite subnets"
  when: "satellite_subnets is defined"
  ansible.builtin.include_tasks: "ensure_subnet.yml"
  loop: "{{ satellite_subnets }}"
  loop_control:
    loop_var: satellite_subnet
  no_log: true
  tags:
    - tags_rhisam
    - tags_infrastructure_config
    - tags_subnets
