---

- name: "Ensure the users for the rhisam configuration"
  ansible.builtin.include_tasks: "ensure_user_group.yml"
  loop: "{{ sat_users_rhisam }}"
  loop_control:
    loop_var: sat_user
  when: "sat_users_rhisam is defined"
  tags:
    - tags_rhisam
    - tags_satellite_management_config
    - tags_sat_users
    - tags_sat_users_rhisam

- name: "Ensure the users for the user configuration"
  ansible.builtin.include_tasks: "ensure_user_group.yml"
  loop: "{{ sat_users_user }}"
  loop_control:
    loop_var: sat_user
  when: "sat_users_user is defined"
  tags:
    - tags_user
    - tags_satellite_management_config
    - tags_sat_users
    - tags_sat_users_user
