---

- name: "Ensure the user roles for the rhisam configuration"
  ansible.builtin.include_tasks: "ensure_user_roles.yml"
  loop: "{{ sat_roles_rhisam }}"
  loop_control:
    loop_var: sat_role
  when: "sat_roles_rhisam is defined"
  tags:
    - tags_rhisam
    - tags_satellite_management_config
    - tags_sat_roles
    - tags_sat_roles_rhisam

- name: "Ensure the user roles for the user configuration"
  ansible.builtin.include_tasks: "ensure_user_group.yml"
  loop: "{{ sat_roles_user }}"
  loop_control:
    loop_var: sat_role
  when: "sat_roles_user is defined"
  tags:
    - tags_user
    - tags_satellite_management_config
    - tags_sat_roles
    - tags_sat_roles_user
