---
# Clone git repositories to the Satellite Server
# This is typically for ansible roles that run at build time - compliance roles.

- name: "Clone the repository locally - {{ gitrepo.repository }}" # noqa: latest[git]
  ansible.builtin.git:
    repo: "{{ gitrepo.repository }}"
    dest: "{{ gitrepo.dest }}"
    clone: "{{ gitrepo.clone | default(omit) }}"
    force: "{{ gitrepo.force | default(omit) }}"
