---

- name: "Configure the rhisam domains"
  when: satellite_domains is defined and (satellite_domains | length) > 0
  ansible.builtin.include_tasks: "ensure_domain.yml"
  loop: "{{ satellite_domains }}"
  loop_control:
    loop_var: satellite_domain
  no_log: true
  tags:
    - tags_rhisam
    - tags_provisioning_config
    - tags_domains
