# This task creates the lifecycle environments defined

- name: "Ensuring the state of the lifecycle environments"
  when: "lifecycle_environments is defined"
  ansible.builtin.include_tasks: "ensure_lifecycle_environment.yml"
  loop: "{{ lifecycle_environments }}"
  loop_control:
    loop_var: lifecycle_environment
  no_log: true
  tags:
    - tags_rhisam
    - tags_content_management_config
    - tags_lifecycle_environments
