---

- name: "Ensure the SCAP tailoring files are configured"
  when: "scap_tailoring_files is defined"
  ansible.builtin.include_tasks: "ensure_scap_tailoring_file.yml"
  loop: "{{ scap_tailoring_files }}"
  loop_control:
    loop_var: scap_tailoring_file
  no_log: true
  tags:
    - tags_rhisam
    - tags_scap_config
    - tags_scap_tailoring_files
