---
# This playbook configures the rhisam provisioning templates
# NOTE: If you are providing templates that will be used with
# ansible downstream, ensure the downstream ansible is properly
# encapsulated. This also applies to any foreman templating
# that may be incompatible with anisble template parsing,
# these occurences should be rare.

- name: "Ensure the state of the provisioning templates"
  when: provisioning_templates is defined and (provisioning_templates | length) > 0
  ansible.builtin.include_tasks: "ensure_provisioning_template.yml"
  loop: "{{ provisioning_templates }}"
  loop_control:
    loop_var: provisioning_template
  no_log: true
  tags:
    - tags_rhisam
    - tags_provisioning_config
    - tags_partition_tables
