---
# set a Satellite general setting to a particular value.

- name: "Configuring {{ _section_fact }}:{{ setting.name }}" # noqa: name[template]
  redhat.satellite.setting:
    username: "{{ satellite_username | default(omit) }}"
    password: "{{ satellite_password | default(omit) }}"
    use_gssapi: "{{ satellite_use_gssapi | default(omit) }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_validate_certs }}"
    name: "{{ setting.name }}"
    value: "{{ setting.value | default(omit) }}" # to reset the value to the default do not provide a value parameter.
