---
# Configure the list of settings.

- name: "Set the current section fact"
  ansible.builtin.set_fact:
    _section_fact: "general"

- name: "Configure the general settings"
  when: settings_general is defined and (settings_general | length) > 0
  ansible.builtin.include_tasks: "ensure_setting.yml"
  loop: "{{ settings_general }}"
  loop_control:
    loop_var: setting
  no_log: false
  tags:
    - tags_rhisam
    - tags_satellite_settings
    - tags_satellite_settings_general

- name: "Set the current section fact"
  ansible.builtin.set_fact:
    _section_fact: "rhcloud"

- name: "Configure the rhcloud settings"
  when: settings_rhcloud is defined and (settings_rhcloud | length) > 0
  ansible.builtin.include_tasks: "ensure_setting.yml"
  loop: "{{ settings_rhcloud }}"
  loop_control:
    loop_var: setting
  no_log: false
  tags:
    - tags_rhisam
    - tags_satellite_settings
    - tags_satellite_settings_rhcloud

- name: "Set the current section fact"
  ansible.builtin.set_fact:
    _section_fact: "authentication"

- name: "Configure the authentication settings"
  when: settings_authentication is defined and (settings_authentication | length) > 0
  ansible.builtin.include_tasks: "ensure_setting.yml"
  loop: "{{ settings_authentication }}"
  loop_control:
    loop_var: setting
  no_log: false
  tags:
    - tags_rhisam
    - tags_satellite_settings
    - tags_satellite_settings_authentication

- name: "Set the current section fact"
  ansible.builtin.set_fact:
    _section_fact: "email"

- name: "Configure the email settings"
  when: settings_email is defined and (settings_email | length) > 0
  ansible.builtin.include_tasks: "ensure_setting.yml"
  loop: "{{ settings_email }}"
  loop_control:
    loop_var: setting
  no_log: false
  tags:
    - tags_rhisam
    - tags_satellite_settings
    - tags_satellite_settings_email

- name: "Set the current section fact"
  ansible.builtin.set_fact:
    _section_fact: "notifications"

- name: "Configure the notification settings"
  when: settings_notification is defined and (settings_notification | length) > 0
  ansible.builtin.include_tasks: "ensure_setting.yml"
  loop: "{{ settings_notification }}"
  loop_control:
    loop_var: setting
  no_log: false
  tags:
    - tags_rhisam
    - tags_satellite_settings
    - tags_satellite_settings_notification

- name: "Set the current section fact"
  ansible.builtin.set_fact:
    _section_fact: "provisioning"

- name: "Configure the provisioning settings"
  when: settings_provisioning is defined and (settings_provisioning | length) > 0
  ansible.builtin.include_tasks: "ensure_setting.yml"
  loop: "{{ settings_provisioning }}"
  loop_control:
    loop_var: setting
  no_log: false
  tags:
    - tags_rhisam
    - tags_satellite_settings
    - tags_satellite_settings_provisioning

- name: "Set the current section fact"
  ansible.builtin.set_fact:
    _section_fact: "facts"

- name: "Configure the facts settings"
  when: settings_facts is defined and (settings_facts | length) > 0
  ansible.builtin.include_tasks: "ensure_setting.yml"
  loop: "{{ settings_facts }}"
  loop_control:
    loop_var: setting
  no_log: false
  tags:
    - tags_rhisam
    - tags_satellite_settings
    - tags_satellite_settings_facts

- name: "Set the current section fact"
  ansible.builtin.set_fact:
    _section_fact: "config_management"

- name: "Configure the config_management settings"
  when: settings_config_management is defined and (settings_config_management | length) > 0
  ansible.builtin.include_tasks: "ensure_setting.yml"
  loop: "{{ settings_config_management }}"
  loop_control:
    loop_var: setting
  no_log: false
  tags:
    - tags_rhisam
    - tags_satellite_settings
    - tags_satellite_settings_config_management

- name: "Set the current section fact"
  ansible.builtin.set_fact:
    _section_fact: "tasks"

- name: "Configure the tasks settings"
  when: settings_tasks is defined and (settings_tasks | length) > 0
  ansible.builtin.include_tasks: "ensure_setting.yml"
  loop: "{{ settings_tasks }}"
  loop_control:
    loop_var: setting
  no_log: false
  tags:
    - tags_rhisam
    - tags_satellite_settings
    - tags_satellite_settings_tasks

- name: "Set the current section fact"
  ansible.builtin.set_fact:
    _section_fact: "remote_execution"

- name: "Configure the remote_execution settings"
  when: settings_remote_execution is defined and (settings_remote_execution | length) > 0
  ansible.builtin.include_tasks: "ensure_setting.yml"
  loop: "{{ settings_remote_execution }}"
  loop_control:
    loop_var: setting
  no_log: false
  tags:
    - tags_rhisam
    - tags_satellite_settings
    - tags_satellite_settings_remote_execution

- name: "Set the current section fact"
  ansible.builtin.set_fact:
    _section_fact: "ansible"

- name: "Configure the ansible settings"
  when: settings_ansible is defined and (settings_ansible | length) > 0
  ansible.builtin.include_tasks: "ensure_setting.yml"
  loop: "{{ settings_ansible }}"
  loop_control:
    loop_var: setting
  no_log: false
  tags:
    - tags_rhisam
    - tags_satellite_settings
    - tags_satellite_settings_ansible

- name: "Set the current section fact"
  ansible.builtin.set_fact:
    _section_fact: "content"

- name: "Configure the content settings"
  when: settings_content is defined and (settings_content | length) > 0
  ansible.builtin.include_tasks: "ensure_setting.yml"
  loop: "{{ settings_content }}"
  loop_control:
    loop_var: setting
  no_log: false
  tags:
    - tags_rhisam
    - tags_satellite_settings
    - tags_satellite_settings_content

- name: "Set the current section fact"
  ansible.builtin.set_fact:
    _section_fact: "boot_disk"

- name: "Configure the boot_disk settings"
  when: settings_boot_disk is defined and (settings_boot_disk | length) > 0
  ansible.builtin.include_tasks: "ensure_setting.yml"
  loop: "{{ settings_boot_disk }}"
  loop_control:
    loop_var: setting
  no_log: false
  tags:
    - tags_rhisam
    - tags_satellite_settings
    - tags_satellite_settings_boot_disk

- name: "Set the current section fact"
  ansible.builtin.set_fact:
    _section_fact: "discovery"

- name: "Configure the discovery settings"
  when: settings_discovery is defined and (settings_discovery | length) > 0
  ansible.builtin.include_tasks: "ensure_setting.yml"
  loop: "{{ settings_discovery }}"
  loop_control:
    loop_var: setting
  no_log: false
  tags:
    - tags_rhisam
    - tags_satellite_settings
    - tags_satellite_settings_discovery

- name: "Set the current section fact"
  ansible.builtin.set_fact:
    _section_fact: "template_sync"

- name: "Configure the template_sync settings"
  when: settings_template_sync is defined and (settings_template_sync | length) > 0
  ansible.builtin.include_tasks: "ensure_setting.yml"
  loop: "{{ settings_template_sync }}"
  loop_control:
    loop_var: setting
  no_log: false
  tags:
    - tags_rhisam
    - tags_satellite_settings
    - tags_satellite_settings_template_sync
