---

# Ensure the state of the defined rhisam and user operating systems.

- name: "Ensure the state of operating systems."
  when: "operating_systems is defined"
  ansible.builtin.include_tasks: "ensure_operating_system.yml"
  loop: "{{ operating_systems }}"
  loop_control:
    loop_var: "operating_system"
  no_log: true
  tags:
    - tags_rhisam
    - tags_provisioning_config
    - tags_operating_systems
