---
# Default Lifecycle environments

lifecycle_environments:
  - name: "Development"
    label: "Development"
    desc: "Content Development - proposed for SOEs"
    org: "{{ satellite_organization }}"
    prior: "Library"

  - name: "Qualification"
    label: "Qualification"
    desc: "Content Qualification of SOEs"
    org: "{{ satellite_organization }}"
    prior: "Development"

  - name: "Production"
    label: "Production"
    desc: "Production Server Approved Content"
    org: "{{ satellite_organization }}"
    prior: "Qualification"

  - name: "Retired"
    label: "Retired"
    desc: "Retired Content - No longer used with Active Servers"
    org: "{{ satellite_organization }}"
    prior: "Production"
