---

- name: "Ensure the state of the satellite organization - {{ satellite_organization.name }}"
  redhat.satellite.organization:
    username: "{{ satellite_username | default(omit) }}"
    password: "{{ satellite_password | default(omit) }}"
    use_gssapi: "{{ satellite_use_gssapi | default(omit) }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_validate_certs }}"
    state: "{{ satellite_organization.state | default(omit) }}"
    description: "{{ satellite_organization.description | default(omit) }}"
    name: "{{ satellite_organization.name }}"
    label: "{{ satellite_organization.label | default(omit) }}"
    select_all_types: "{{ satellite_organization.select_all_types | default(omit) }}"
    ignore_types: "{{ satellite_organization.ignore_types | default(omit) }}"
    parameters: "{{ satellite_organization.parameters | default('[]') }}"
